### PR TITLE
build(deps-dev): plugin updates

### PR DESCRIPTION
**Pull request by dschach**
docs(ApexDox): update ApexDox d/t Prettier update

ci: add GitHub action on pull request with test deploy & test run

### CODE REVIEW

**Comment by dschach** [comment]
@codefriar We need to put a secret in this repo, `SALESFORCE_AUTH_URL`, that has the authorization URL for a dev hub user.

**Comment by codefriar** [comment]
@dschach I've not merged this yet, mostly because I don't have access to an org we can use as a dev hub longer than 30 days.

**Comment by dschach** [comment]
I have an org, but I'll need permission to update the secret in this repo

**Comment by codefriar** [comment]
Will hit you up privately about this.

**Comment by dschach** [comment]
@codefriar Since secrets aren't passed to workflows triggered by pull requests from forks, this will never be successful. But it did pass on my fork, so I know it works. It is ready to merge.

**Pull request merged**
